/*
 * Tceon.com Inc.
 * Copyright (c) 2009 All Rights Reserved.
 */
package com.taicang.mscz.report.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.taicang.mscz.report.common.dal.daointerface.ReportFieldMappingDAO;

// auto generated imports
import com.taicang.mscz.report.common.dal.dataobject.ReportFieldMappingDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import com.taicang.mscz.report.common.dal.dataobject.ReportFieldMappingDO;

/**
 * An ibatis based implementation of dao interface <tt>com.taicang.mscz.report.common.dal.daointerface.ReportFieldMappingDAO</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/report_field_mapping.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class IbatisReportFieldMappingDAO extends SqlMapClientDaoSupport implements ReportFieldMappingDAO {
	/**
	 *  Query DB table <tt>report_field_mapping</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from report_field_mapping where (report_id = ?)</tt>
	 *
	 *	@param reportId
	 *	@return List<ReportFieldMappingDO>
	 *	@throws DataAccessException
	 */	 
    public List<ReportFieldMappingDO> getByReportId(int reportId) throws DataAccessException {
        Integer param = new Integer(reportId);
        return getSqlMapClientTemplate().queryForList("MS-REPORT-FIELD-MAPPING-GET-BY-REPORT-ID", param);

    }

	/**
	 *  Insert one <tt>ReportFieldMappingDO</tt> object to DB table <tt>report_field_mapping</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into report_field_mapping(report_id,biz_field,db_field) values (?, ?, ?)</tt>
	 *
	 *	@param reportFieldMapping
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(ReportFieldMappingDO reportFieldMapping) throws DataAccessException {
    	if (reportFieldMapping == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-REPORT-FIELD-MAPPING-INSERT", reportFieldMapping);

        return reportFieldMapping.getId();
    }

}