/*
 * Tceon.com Inc.
 * Copyright (c) 2009 All Rights Reserved.
 */
package com.taicang.mscz.report.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.taicang.mscz.report.common.dal.daointerface.ReportDimensionValueDAO;

// auto generated imports
import com.taicang.mscz.report.common.dal.dataobject.ReportDimensionValueDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import com.taicang.mscz.report.common.dal.dataobject.ReportDimensionValueDO;

/**
 * An ibatis based implementation of dao interface <tt>com.taicang.mscz.report.common.dal.daointerface.ReportDimensionValueDAO</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/report_dimension_value.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class IbatisReportDimensionValueDAO extends SqlMapClientDaoSupport implements ReportDimensionValueDAO {
	/**
	 *  Query DB table <tt>report_dimension_value</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from report_dimension_value where (report_dim_id = ?)</tt>
	 *
	 *	@param reportDimId
	 *	@return List<ReportDimensionValueDO>
	 *	@throws DataAccessException
	 */	 
    public List<ReportDimensionValueDO> getByDimId(int reportDimId) throws DataAccessException {
        Integer param = new Integer(reportDimId);
        return getSqlMapClientTemplate().queryForList("MS-REPORT-DIMENSION-VALUE-GET-BY-DIM-ID", param);

    }

	/**
	 *  Insert one <tt>ReportDimensionValueDO</tt> object to DB table <tt>report_dimension_value</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into report_dimension_value(report_dim_id,dim_value) values (?, ?)</tt>
	 *
	 *	@param reportDimensionValue
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(ReportDimensionValueDO reportDimensionValue) throws DataAccessException {
    	if (reportDimensionValue == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlMapClientTemplate().insert("MS-REPORT-DIMENSION-VALUE-INSERT", reportDimensionValue);

        return reportDimensionValue.getId();
    }

}