/*
 * Tceon.com Inc.
 * Copyright (c) 2009 All Rights Reserved.
 */
package com.taicang.mscz.report.common.dal.dataobject;

// auto generated imports

/**
 * A data object class directly models database table <tt>report_dimension_value</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/report_dimension_value.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class ReportDimensionValueDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>report_dim_id</tt>.
	 */
	private int reportDimId;

	/**
	 * This property corresponds to db column <tt>dim_value</tt>.
	 */
	private String dimValue;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>reportDimId</tt>.
     *
     * @return property value of reportDimId
     */
	public int getReportDimId() {
		return reportDimId;
	}
	
	/**
	 * Setter method for property <tt>reportDimId</tt>.
	 * 
	 * @param reportDimId value to be assigned to property reportDimId
     */
	public void setReportDimId(int reportDimId) {
		this.reportDimId = reportDimId;
	}

    /**
     * Getter method for property <tt>dimValue</tt>.
     *
     * @return property value of dimValue
     */
	public String getDimValue() {
		return dimValue;
	}
	
	/**
	 * Setter method for property <tt>dimValue</tt>.
	 * 
	 * @param dimValue value to be assigned to property dimValue
     */
	public void setDimValue(String dimValue) {
		this.dimValue = dimValue;
	}
}
