/*
 * Tceon.com Inc.
 * Copyright (c) 2009 All Rights Reserved.
 */
package com.taicang.mscz.report.common.dal.dataobject;

// auto generated imports

/**
 * A data object class directly models database table <tt>report_field_mapping</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/report_field_mapping.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class ReportFieldMappingDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>report_id</tt>.
	 */
	private int reportId;

	/**
	 * This property corresponds to db column <tt>biz_field</tt>.
	 */
	private String bizField;

	/**
	 * This property corresponds to db column <tt>db_field</tt>.
	 */
	private String dbField;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>reportId</tt>.
     *
     * @return property value of reportId
     */
	public int getReportId() {
		return reportId;
	}
	
	/**
	 * Setter method for property <tt>reportId</tt>.
	 * 
	 * @param reportId value to be assigned to property reportId
     */
	public void setReportId(int reportId) {
		this.reportId = reportId;
	}

    /**
     * Getter method for property <tt>bizField</tt>.
     *
     * @return property value of bizField
     */
	public String getBizField() {
		return bizField;
	}
	
	/**
	 * Setter method for property <tt>bizField</tt>.
	 * 
	 * @param bizField value to be assigned to property bizField
     */
	public void setBizField(String bizField) {
		this.bizField = bizField;
	}

    /**
     * Getter method for property <tt>dbField</tt>.
     *
     * @return property value of dbField
     */
	public String getDbField() {
		return dbField;
	}
	
	/**
	 * Setter method for property <tt>dbField</tt>.
	 * 
	 * @param dbField value to be assigned to property dbField
     */
	public void setDbField(String dbField) {
		this.dbField = dbField;
	}
}
