/*
 * Tceon.com Inc.
 * Copyright (c) 2009 All Rights Reserved.
 */
package com.taicang.mscz.report.common.dal.dataobject;

// auto generated imports

/**
 * A data object class directly models database table <tt>unit</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/unit.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class UnitDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>report_id</tt>.
	 */
	private int reportId;

	/**
	 * This property corresponds to db column <tt>F1</tt>.
	 */
	private String f1;

	/**
	 * This property corresponds to db column <tt>F2</tt>.
	 */
	private String f2;

	/**
	 * This property corresponds to db column <tt>F3</tt>.
	 */
	private String f3;

	/**
	 * This property corresponds to db column <tt>F4</tt>.
	 */
	private String f4;

	/**
	 * This property corresponds to db column <tt>F5</tt>.
	 */
	private String f5;

	/**
	 * This property corresponds to db column <tt>F6</tt>.
	 */
	private String f6;

	/**
	 * This property corresponds to db column <tt>F7</tt>.
	 */
	private String f7;

	/**
	 * This property corresponds to db column <tt>F8</tt>.
	 */
	private String f8;

	/**
	 * This property corresponds to db column <tt>F9</tt>.
	 */
	private String f9;

	/**
	 * This property corresponds to db column <tt>F10</tt>.
	 */
	private String f10;

	/**
	 * This property corresponds to db column <tt>F11</tt>.
	 */
	private String f11;

	/**
	 * This property corresponds to db column <tt>F12</tt>.
	 */
	private String f12;

	/**
	 * This property corresponds to db column <tt>F13</tt>.
	 */
	private String f13;

	/**
	 * This property corresponds to db column <tt>F14</tt>.
	 */
	private String f14;

	/**
	 * This property corresponds to db column <tt>F15</tt>.
	 */
	private String f15;

	/**
	 * This property corresponds to db column <tt>F16</tt>.
	 */
	private String f16;

	/**
	 * This property corresponds to db column <tt>F17</tt>.
	 */
	private String f17;

	/**
	 * This property corresponds to db column <tt>F18</tt>.
	 */
	private String f18;

	/**
	 * This property corresponds to db column <tt>F19</tt>.
	 */
	private String f19;

	/**
	 * This property corresponds to db column <tt>F20</tt>.
	 */
	private String f20;

	/**
	 * This property corresponds to db column <tt>F21</tt>.
	 */
	private String f21;

	/**
	 * This property corresponds to db column <tt>F22</tt>.
	 */
	private String f22;

	/**
	 * This property corresponds to db column <tt>F23</tt>.
	 */
	private String f23;

	/**
	 * This property corresponds to db column <tt>F24</tt>.
	 */
	private String f24;

	/**
	 * This property corresponds to db column <tt>F25</tt>.
	 */
	private String f25;

	/**
	 * This property corresponds to db column <tt>F26</tt>.
	 */
	private String f26;

	/**
	 * This property corresponds to db column <tt>F27</tt>.
	 */
	private String f27;

	/**
	 * This property corresponds to db column <tt>F28</tt>.
	 */
	private String f28;

	/**
	 * This property corresponds to db column <tt>F29</tt>.
	 */
	private String f29;

	/**
	 * This property corresponds to db column <tt>F30</tt>.
	 */
	private String f30;

	/**
	 * This property corresponds to db column <tt>F31</tt>.
	 */
	private String f31;

	/**
	 * This property corresponds to db column <tt>F32</tt>.
	 */
	private String f32;

	/**
	 * This property corresponds to db column <tt>F33</tt>.
	 */
	private String f33;

	/**
	 * This property corresponds to db column <tt>F34</tt>.
	 */
	private String f34;

	/**
	 * This property corresponds to db column <tt>F35</tt>.
	 */
	private String f35;

	/**
	 * This property corresponds to db column <tt>F36</tt>.
	 */
	private String f36;

	/**
	 * This property corresponds to db column <tt>F37</tt>.
	 */
	private String f37;

	/**
	 * This property corresponds to db column <tt>F38</tt>.
	 */
	private String f38;

	/**
	 * This property corresponds to db column <tt>F39</tt>.
	 */
	private String f39;

	/**
	 * This property corresponds to db column <tt>F40</tt>.
	 */
	private String f40;

	/**
	 * This property corresponds to db column <tt>F41</tt>.
	 */
	private String f41;

	/**
	 * This property corresponds to db column <tt>F42</tt>.
	 */
	private String f42;

	/**
	 * This property corresponds to db column <tt>F43</tt>.
	 */
	private String f43;

	/**
	 * This property corresponds to db column <tt>F44</tt>.
	 */
	private String f44;

	/**
	 * This property corresponds to db column <tt>F45</tt>.
	 */
	private String f45;

	/**
	 * This property corresponds to db column <tt>F46</tt>.
	 */
	private String f46;

	/**
	 * This property corresponds to db column <tt>F47</tt>.
	 */
	private String f47;

	/**
	 * This property corresponds to db column <tt>F48</tt>.
	 */
	private String f48;

	/**
	 * This property corresponds to db column <tt>F49</tt>.
	 */
	private String f49;

	/**
	 * This property corresponds to db column <tt>F50</tt>.
	 */
	private String f50;

	/**
	 * This property corresponds to db column <tt>F51</tt>.
	 */
	private String f51;

	/**
	 * This property corresponds to db column <tt>F52</tt>.
	 */
	private String f52;

	/**
	 * This property corresponds to db column <tt>F53</tt>.
	 */
	private String f53;

	/**
	 * This property corresponds to db column <tt>F54</tt>.
	 */
	private String f54;

	/**
	 * This property corresponds to db column <tt>F55</tt>.
	 */
	private String f55;

	/**
	 * This property corresponds to db column <tt>F56</tt>.
	 */
	private String f56;

	/**
	 * This property corresponds to db column <tt>F57</tt>.
	 */
	private String f57;

	/**
	 * This property corresponds to db column <tt>F58</tt>.
	 */
	private String f58;

	/**
	 * This property corresponds to db column <tt>F59</tt>.
	 */
	private String f59;

	/**
	 * This property corresponds to db column <tt>F60</tt>.
	 */
	private String f60;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>reportId</tt>.
     *
     * @return property value of reportId
     */
	public int getReportId() {
		return reportId;
	}
	
	/**
	 * Setter method for property <tt>reportId</tt>.
	 * 
	 * @param reportId value to be assigned to property reportId
     */
	public void setReportId(int reportId) {
		this.reportId = reportId;
	}

    /**
     * Getter method for property <tt>f1</tt>.
     *
     * @return property value of f1
     */
	public String getF1() {
		return f1;
	}
	
	/**
	 * Setter method for property <tt>f1</tt>.
	 * 
	 * @param f1 value to be assigned to property f1
     */
	public void setF1(String f1) {
		this.f1 = f1;
	}

    /**
     * Getter method for property <tt>f2</tt>.
     *
     * @return property value of f2
     */
	public String getF2() {
		return f2;
	}
	
	/**
	 * Setter method for property <tt>f2</tt>.
	 * 
	 * @param f2 value to be assigned to property f2
     */
	public void setF2(String f2) {
		this.f2 = f2;
	}

    /**
     * Getter method for property <tt>f3</tt>.
     *
     * @return property value of f3
     */
	public String getF3() {
		return f3;
	}
	
	/**
	 * Setter method for property <tt>f3</tt>.
	 * 
	 * @param f3 value to be assigned to property f3
     */
	public void setF3(String f3) {
		this.f3 = f3;
	}

    /**
     * Getter method for property <tt>f4</tt>.
     *
     * @return property value of f4
     */
	public String getF4() {
		return f4;
	}
	
	/**
	 * Setter method for property <tt>f4</tt>.
	 * 
	 * @param f4 value to be assigned to property f4
     */
	public void setF4(String f4) {
		this.f4 = f4;
	}

    /**
     * Getter method for property <tt>f5</tt>.
     *
     * @return property value of f5
     */
	public String getF5() {
		return f5;
	}
	
	/**
	 * Setter method for property <tt>f5</tt>.
	 * 
	 * @param f5 value to be assigned to property f5
     */
	public void setF5(String f5) {
		this.f5 = f5;
	}

    /**
     * Getter method for property <tt>f6</tt>.
     *
     * @return property value of f6
     */
	public String getF6() {
		return f6;
	}
	
	/**
	 * Setter method for property <tt>f6</tt>.
	 * 
	 * @param f6 value to be assigned to property f6
     */
	public void setF6(String f6) {
		this.f6 = f6;
	}

    /**
     * Getter method for property <tt>f7</tt>.
     *
     * @return property value of f7
     */
	public String getF7() {
		return f7;
	}
	
	/**
	 * Setter method for property <tt>f7</tt>.
	 * 
	 * @param f7 value to be assigned to property f7
     */
	public void setF7(String f7) {
		this.f7 = f7;
	}

    /**
     * Getter method for property <tt>f8</tt>.
     *
     * @return property value of f8
     */
	public String getF8() {
		return f8;
	}
	
	/**
	 * Setter method for property <tt>f8</tt>.
	 * 
	 * @param f8 value to be assigned to property f8
     */
	public void setF8(String f8) {
		this.f8 = f8;
	}

    /**
     * Getter method for property <tt>f9</tt>.
     *
     * @return property value of f9
     */
	public String getF9() {
		return f9;
	}
	
	/**
	 * Setter method for property <tt>f9</tt>.
	 * 
	 * @param f9 value to be assigned to property f9
     */
	public void setF9(String f9) {
		this.f9 = f9;
	}

    /**
     * Getter method for property <tt>f10</tt>.
     *
     * @return property value of f10
     */
	public String getF10() {
		return f10;
	}
	
	/**
	 * Setter method for property <tt>f10</tt>.
	 * 
	 * @param f10 value to be assigned to property f10
     */
	public void setF10(String f10) {
		this.f10 = f10;
	}

    /**
     * Getter method for property <tt>f11</tt>.
     *
     * @return property value of f11
     */
	public String getF11() {
		return f11;
	}
	
	/**
	 * Setter method for property <tt>f11</tt>.
	 * 
	 * @param f11 value to be assigned to property f11
     */
	public void setF11(String f11) {
		this.f11 = f11;
	}

    /**
     * Getter method for property <tt>f12</tt>.
     *
     * @return property value of f12
     */
	public String getF12() {
		return f12;
	}
	
	/**
	 * Setter method for property <tt>f12</tt>.
	 * 
	 * @param f12 value to be assigned to property f12
     */
	public void setF12(String f12) {
		this.f12 = f12;
	}

    /**
     * Getter method for property <tt>f13</tt>.
     *
     * @return property value of f13
     */
	public String getF13() {
		return f13;
	}
	
	/**
	 * Setter method for property <tt>f13</tt>.
	 * 
	 * @param f13 value to be assigned to property f13
     */
	public void setF13(String f13) {
		this.f13 = f13;
	}

    /**
     * Getter method for property <tt>f14</tt>.
     *
     * @return property value of f14
     */
	public String getF14() {
		return f14;
	}
	
	/**
	 * Setter method for property <tt>f14</tt>.
	 * 
	 * @param f14 value to be assigned to property f14
     */
	public void setF14(String f14) {
		this.f14 = f14;
	}

    /**
     * Getter method for property <tt>f15</tt>.
     *
     * @return property value of f15
     */
	public String getF15() {
		return f15;
	}
	
	/**
	 * Setter method for property <tt>f15</tt>.
	 * 
	 * @param f15 value to be assigned to property f15
     */
	public void setF15(String f15) {
		this.f15 = f15;
	}

    /**
     * Getter method for property <tt>f16</tt>.
     *
     * @return property value of f16
     */
	public String getF16() {
		return f16;
	}
	
	/**
	 * Setter method for property <tt>f16</tt>.
	 * 
	 * @param f16 value to be assigned to property f16
     */
	public void setF16(String f16) {
		this.f16 = f16;
	}

    /**
     * Getter method for property <tt>f17</tt>.
     *
     * @return property value of f17
     */
	public String getF17() {
		return f17;
	}
	
	/**
	 * Setter method for property <tt>f17</tt>.
	 * 
	 * @param f17 value to be assigned to property f17
     */
	public void setF17(String f17) {
		this.f17 = f17;
	}

    /**
     * Getter method for property <tt>f18</tt>.
     *
     * @return property value of f18
     */
	public String getF18() {
		return f18;
	}
	
	/**
	 * Setter method for property <tt>f18</tt>.
	 * 
	 * @param f18 value to be assigned to property f18
     */
	public void setF18(String f18) {
		this.f18 = f18;
	}

    /**
     * Getter method for property <tt>f19</tt>.
     *
     * @return property value of f19
     */
	public String getF19() {
		return f19;
	}
	
	/**
	 * Setter method for property <tt>f19</tt>.
	 * 
	 * @param f19 value to be assigned to property f19
     */
	public void setF19(String f19) {
		this.f19 = f19;
	}

    /**
     * Getter method for property <tt>f20</tt>.
     *
     * @return property value of f20
     */
	public String getF20() {
		return f20;
	}
	
	/**
	 * Setter method for property <tt>f20</tt>.
	 * 
	 * @param f20 value to be assigned to property f20
     */
	public void setF20(String f20) {
		this.f20 = f20;
	}

    /**
     * Getter method for property <tt>f21</tt>.
     *
     * @return property value of f21
     */
	public String getF21() {
		return f21;
	}
	
	/**
	 * Setter method for property <tt>f21</tt>.
	 * 
	 * @param f21 value to be assigned to property f21
     */
	public void setF21(String f21) {
		this.f21 = f21;
	}

    /**
     * Getter method for property <tt>f22</tt>.
     *
     * @return property value of f22
     */
	public String getF22() {
		return f22;
	}
	
	/**
	 * Setter method for property <tt>f22</tt>.
	 * 
	 * @param f22 value to be assigned to property f22
     */
	public void setF22(String f22) {
		this.f22 = f22;
	}

    /**
     * Getter method for property <tt>f23</tt>.
     *
     * @return property value of f23
     */
	public String getF23() {
		return f23;
	}
	
	/**
	 * Setter method for property <tt>f23</tt>.
	 * 
	 * @param f23 value to be assigned to property f23
     */
	public void setF23(String f23) {
		this.f23 = f23;
	}

    /**
     * Getter method for property <tt>f24</tt>.
     *
     * @return property value of f24
     */
	public String getF24() {
		return f24;
	}
	
	/**
	 * Setter method for property <tt>f24</tt>.
	 * 
	 * @param f24 value to be assigned to property f24
     */
	public void setF24(String f24) {
		this.f24 = f24;
	}

    /**
     * Getter method for property <tt>f25</tt>.
     *
     * @return property value of f25
     */
	public String getF25() {
		return f25;
	}
	
	/**
	 * Setter method for property <tt>f25</tt>.
	 * 
	 * @param f25 value to be assigned to property f25
     */
	public void setF25(String f25) {
		this.f25 = f25;
	}

    /**
     * Getter method for property <tt>f26</tt>.
     *
     * @return property value of f26
     */
	public String getF26() {
		return f26;
	}
	
	/**
	 * Setter method for property <tt>f26</tt>.
	 * 
	 * @param f26 value to be assigned to property f26
     */
	public void setF26(String f26) {
		this.f26 = f26;
	}

    /**
     * Getter method for property <tt>f27</tt>.
     *
     * @return property value of f27
     */
	public String getF27() {
		return f27;
	}
	
	/**
	 * Setter method for property <tt>f27</tt>.
	 * 
	 * @param f27 value to be assigned to property f27
     */
	public void setF27(String f27) {
		this.f27 = f27;
	}

    /**
     * Getter method for property <tt>f28</tt>.
     *
     * @return property value of f28
     */
	public String getF28() {
		return f28;
	}
	
	/**
	 * Setter method for property <tt>f28</tt>.
	 * 
	 * @param f28 value to be assigned to property f28
     */
	public void setF28(String f28) {
		this.f28 = f28;
	}

    /**
     * Getter method for property <tt>f29</tt>.
     *
     * @return property value of f29
     */
	public String getF29() {
		return f29;
	}
	
	/**
	 * Setter method for property <tt>f29</tt>.
	 * 
	 * @param f29 value to be assigned to property f29
     */
	public void setF29(String f29) {
		this.f29 = f29;
	}

    /**
     * Getter method for property <tt>f30</tt>.
     *
     * @return property value of f30
     */
	public String getF30() {
		return f30;
	}
	
	/**
	 * Setter method for property <tt>f30</tt>.
	 * 
	 * @param f30 value to be assigned to property f30
     */
	public void setF30(String f30) {
		this.f30 = f30;
	}

    /**
     * Getter method for property <tt>f31</tt>.
     *
     * @return property value of f31
     */
	public String getF31() {
		return f31;
	}
	
	/**
	 * Setter method for property <tt>f31</tt>.
	 * 
	 * @param f31 value to be assigned to property f31
     */
	public void setF31(String f31) {
		this.f31 = f31;
	}

    /**
     * Getter method for property <tt>f32</tt>.
     *
     * @return property value of f32
     */
	public String getF32() {
		return f32;
	}
	
	/**
	 * Setter method for property <tt>f32</tt>.
	 * 
	 * @param f32 value to be assigned to property f32
     */
	public void setF32(String f32) {
		this.f32 = f32;
	}

    /**
     * Getter method for property <tt>f33</tt>.
     *
     * @return property value of f33
     */
	public String getF33() {
		return f33;
	}
	
	/**
	 * Setter method for property <tt>f33</tt>.
	 * 
	 * @param f33 value to be assigned to property f33
     */
	public void setF33(String f33) {
		this.f33 = f33;
	}

    /**
     * Getter method for property <tt>f34</tt>.
     *
     * @return property value of f34
     */
	public String getF34() {
		return f34;
	}
	
	/**
	 * Setter method for property <tt>f34</tt>.
	 * 
	 * @param f34 value to be assigned to property f34
     */
	public void setF34(String f34) {
		this.f34 = f34;
	}

    /**
     * Getter method for property <tt>f35</tt>.
     *
     * @return property value of f35
     */
	public String getF35() {
		return f35;
	}
	
	/**
	 * Setter method for property <tt>f35</tt>.
	 * 
	 * @param f35 value to be assigned to property f35
     */
	public void setF35(String f35) {
		this.f35 = f35;
	}

    /**
     * Getter method for property <tt>f36</tt>.
     *
     * @return property value of f36
     */
	public String getF36() {
		return f36;
	}
	
	/**
	 * Setter method for property <tt>f36</tt>.
	 * 
	 * @param f36 value to be assigned to property f36
     */
	public void setF36(String f36) {
		this.f36 = f36;
	}

    /**
     * Getter method for property <tt>f37</tt>.
     *
     * @return property value of f37
     */
	public String getF37() {
		return f37;
	}
	
	/**
	 * Setter method for property <tt>f37</tt>.
	 * 
	 * @param f37 value to be assigned to property f37
     */
	public void setF37(String f37) {
		this.f37 = f37;
	}

    /**
     * Getter method for property <tt>f38</tt>.
     *
     * @return property value of f38
     */
	public String getF38() {
		return f38;
	}
	
	/**
	 * Setter method for property <tt>f38</tt>.
	 * 
	 * @param f38 value to be assigned to property f38
     */
	public void setF38(String f38) {
		this.f38 = f38;
	}

    /**
     * Getter method for property <tt>f39</tt>.
     *
     * @return property value of f39
     */
	public String getF39() {
		return f39;
	}
	
	/**
	 * Setter method for property <tt>f39</tt>.
	 * 
	 * @param f39 value to be assigned to property f39
     */
	public void setF39(String f39) {
		this.f39 = f39;
	}

    /**
     * Getter method for property <tt>f40</tt>.
     *
     * @return property value of f40
     */
	public String getF40() {
		return f40;
	}
	
	/**
	 * Setter method for property <tt>f40</tt>.
	 * 
	 * @param f40 value to be assigned to property f40
     */
	public void setF40(String f40) {
		this.f40 = f40;
	}

    /**
     * Getter method for property <tt>f41</tt>.
     *
     * @return property value of f41
     */
	public String getF41() {
		return f41;
	}
	
	/**
	 * Setter method for property <tt>f41</tt>.
	 * 
	 * @param f41 value to be assigned to property f41
     */
	public void setF41(String f41) {
		this.f41 = f41;
	}

    /**
     * Getter method for property <tt>f42</tt>.
     *
     * @return property value of f42
     */
	public String getF42() {
		return f42;
	}
	
	/**
	 * Setter method for property <tt>f42</tt>.
	 * 
	 * @param f42 value to be assigned to property f42
     */
	public void setF42(String f42) {
		this.f42 = f42;
	}

    /**
     * Getter method for property <tt>f43</tt>.
     *
     * @return property value of f43
     */
	public String getF43() {
		return f43;
	}
	
	/**
	 * Setter method for property <tt>f43</tt>.
	 * 
	 * @param f43 value to be assigned to property f43
     */
	public void setF43(String f43) {
		this.f43 = f43;
	}

    /**
     * Getter method for property <tt>f44</tt>.
     *
     * @return property value of f44
     */
	public String getF44() {
		return f44;
	}
	
	/**
	 * Setter method for property <tt>f44</tt>.
	 * 
	 * @param f44 value to be assigned to property f44
     */
	public void setF44(String f44) {
		this.f44 = f44;
	}

    /**
     * Getter method for property <tt>f45</tt>.
     *
     * @return property value of f45
     */
	public String getF45() {
		return f45;
	}
	
	/**
	 * Setter method for property <tt>f45</tt>.
	 * 
	 * @param f45 value to be assigned to property f45
     */
	public void setF45(String f45) {
		this.f45 = f45;
	}

    /**
     * Getter method for property <tt>f46</tt>.
     *
     * @return property value of f46
     */
	public String getF46() {
		return f46;
	}
	
	/**
	 * Setter method for property <tt>f46</tt>.
	 * 
	 * @param f46 value to be assigned to property f46
     */
	public void setF46(String f46) {
		this.f46 = f46;
	}

    /**
     * Getter method for property <tt>f47</tt>.
     *
     * @return property value of f47
     */
	public String getF47() {
		return f47;
	}
	
	/**
	 * Setter method for property <tt>f47</tt>.
	 * 
	 * @param f47 value to be assigned to property f47
     */
	public void setF47(String f47) {
		this.f47 = f47;
	}

    /**
     * Getter method for property <tt>f48</tt>.
     *
     * @return property value of f48
     */
	public String getF48() {
		return f48;
	}
	
	/**
	 * Setter method for property <tt>f48</tt>.
	 * 
	 * @param f48 value to be assigned to property f48
     */
	public void setF48(String f48) {
		this.f48 = f48;
	}

    /**
     * Getter method for property <tt>f49</tt>.
     *
     * @return property value of f49
     */
	public String getF49() {
		return f49;
	}
	
	/**
	 * Setter method for property <tt>f49</tt>.
	 * 
	 * @param f49 value to be assigned to property f49
     */
	public void setF49(String f49) {
		this.f49 = f49;
	}

    /**
     * Getter method for property <tt>f50</tt>.
     *
     * @return property value of f50
     */
	public String getF50() {
		return f50;
	}
	
	/**
	 * Setter method for property <tt>f50</tt>.
	 * 
	 * @param f50 value to be assigned to property f50
     */
	public void setF50(String f50) {
		this.f50 = f50;
	}

    /**
     * Getter method for property <tt>f51</tt>.
     *
     * @return property value of f51
     */
	public String getF51() {
		return f51;
	}
	
	/**
	 * Setter method for property <tt>f51</tt>.
	 * 
	 * @param f51 value to be assigned to property f51
     */
	public void setF51(String f51) {
		this.f51 = f51;
	}

    /**
     * Getter method for property <tt>f52</tt>.
     *
     * @return property value of f52
     */
	public String getF52() {
		return f52;
	}
	
	/**
	 * Setter method for property <tt>f52</tt>.
	 * 
	 * @param f52 value to be assigned to property f52
     */
	public void setF52(String f52) {
		this.f52 = f52;
	}

    /**
     * Getter method for property <tt>f53</tt>.
     *
     * @return property value of f53
     */
	public String getF53() {
		return f53;
	}
	
	/**
	 * Setter method for property <tt>f53</tt>.
	 * 
	 * @param f53 value to be assigned to property f53
     */
	public void setF53(String f53) {
		this.f53 = f53;
	}

    /**
     * Getter method for property <tt>f54</tt>.
     *
     * @return property value of f54
     */
	public String getF54() {
		return f54;
	}
	
	/**
	 * Setter method for property <tt>f54</tt>.
	 * 
	 * @param f54 value to be assigned to property f54
     */
	public void setF54(String f54) {
		this.f54 = f54;
	}

    /**
     * Getter method for property <tt>f55</tt>.
     *
     * @return property value of f55
     */
	public String getF55() {
		return f55;
	}
	
	/**
	 * Setter method for property <tt>f55</tt>.
	 * 
	 * @param f55 value to be assigned to property f55
     */
	public void setF55(String f55) {
		this.f55 = f55;
	}

    /**
     * Getter method for property <tt>f56</tt>.
     *
     * @return property value of f56
     */
	public String getF56() {
		return f56;
	}
	
	/**
	 * Setter method for property <tt>f56</tt>.
	 * 
	 * @param f56 value to be assigned to property f56
     */
	public void setF56(String f56) {
		this.f56 = f56;
	}

    /**
     * Getter method for property <tt>f57</tt>.
     *
     * @return property value of f57
     */
	public String getF57() {
		return f57;
	}
	
	/**
	 * Setter method for property <tt>f57</tt>.
	 * 
	 * @param f57 value to be assigned to property f57
     */
	public void setF57(String f57) {
		this.f57 = f57;
	}

    /**
     * Getter method for property <tt>f58</tt>.
     *
     * @return property value of f58
     */
	public String getF58() {
		return f58;
	}
	
	/**
	 * Setter method for property <tt>f58</tt>.
	 * 
	 * @param f58 value to be assigned to property f58
     */
	public void setF58(String f58) {
		this.f58 = f58;
	}

    /**
     * Getter method for property <tt>f59</tt>.
     *
     * @return property value of f59
     */
	public String getF59() {
		return f59;
	}
	
	/**
	 * Setter method for property <tt>f59</tt>.
	 * 
	 * @param f59 value to be assigned to property f59
     */
	public void setF59(String f59) {
		this.f59 = f59;
	}

    /**
     * Getter method for property <tt>f60</tt>.
     *
     * @return property value of f60
     */
	public String getF60() {
		return f60;
	}
	
	/**
	 * Setter method for property <tt>f60</tt>.
	 * 
	 * @param f60 value to be assigned to property f60
     */
	public void setF60(String f60) {
		this.f60 = f60;
	}
}
