/*
 * Tceon.com Inc.
 * Copyright (c) 2009 All Rights Reserved.
 */
package com.taicang.mscz.report.common.dal.daointerface;

// auto generated imports
import org.springframework.dao.DataAccessException;

import com.taicang.mscz.report.common.dal.dataobject.ReportDO;
import com.taicang.mscz.report.dal.util.PageList;

/**
 * A dao interface provides methods to access database table <tt>report</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/report.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public interface ReportDAO {
	/**
	 *  Query DB table <tt>report</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from report where (name = ?)</tt>
	 *
	 *	@param name
	 *	@return ReportDO
	 *	@throws DataAccessException
	 */	 
    public ReportDO getByName(String name) throws DataAccessException;

	/**
	 *  Query DB table <tt>report</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from report where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return ReportDO
	 *	@throws DataAccessException
	 */	 
    public ReportDO getById(int id) throws DataAccessException;

	/**
	 *  Insert one <tt>ReportDO</tt> object to DB table <tt>report</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into report(name,submitter,create_time,modify_time) values (?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)</tt>
	 *
	 *	@param report
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(ReportDO report) throws DataAccessException;

	/**
	 *  Query DB table <tt>report</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from report</tt>
	 *
	 *	@param submitter
	 *	@param name
	 *	@param pageSize
	 *	@param pageNum
	 *	@return PageList
	 *	@throws DataAccessException
	 */	 
    public PageList getByCondition(String submitter, String name, int pageSize, int pageNum) throws DataAccessException;

}